# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simulation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10simulation.proto\x12\nsimulation\"\x83\x01\n\x07Request\x12\x14\n\x0cmessage_type\x18\x01 \x01(\x03\x12\n\n\x02id\x18\x02 \x01(\x03\x12\x11\n\tdata_time\x18\x03 \x01(\x03\x12\x13\n\x0bnum_workers\x18\x04 \x01(\x03\x12\x15\n\rworker_status\x18\x05 \x01(\x08\x12\x17\n\x0f\x61\x64j_worker_time\x18\x06 \x01(\x03\"\n\n\x08Response\"?\n\x05\x42\x61tch\x12%\n\x08requests\x18\x01 \x03(\x0b\x32\x13.simulation.Request\x12\x0f\n\x07\x63ontrol\x18\x02 \x01(\x08\"<\n\rBatchResponse\x12\x11\n\tend_times\x18\x01 \x03(\x03\x12\x18\n\x10\x61\x64j_worker_times\x18\x02 \x03(\x03\x32\x87\x01\n\tInference\x12:\n\x0bSendRequest\x12\x13.simulation.Request\x1a\x14.simulation.Response\"\x00\x12>\n\x0cProcessBatch\x12\x11.simulation.Batch\x1a\x19.simulation.BatchResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simulation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=33
  _REQUEST._serialized_end=164
  _RESPONSE._serialized_start=166
  _RESPONSE._serialized_end=176
  _BATCH._serialized_start=178
  _BATCH._serialized_end=241
  _BATCHRESPONSE._serialized_start=243
  _BATCHRESPONSE._serialized_end=303
  _INFERENCE._serialized_start=306
  _INFERENCE._serialized_end=441
# @@protoc_insertion_point(module_scope)
